// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH9bcg-xkt7vIBrjyuiPRqSltrJ-TFI0k',
    appId: '1:177666494702:web:5f130f2bdbdc68706ae3ff',
    messagingSenderId: '177666494702',
    projectId: 'stusama-revisi-ui',
    authDomain: 'stusama-revisi-ui.firebaseapp.com',
    storageBucket: 'stusama-revisi-ui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJkqAfkUnIe_vn8EStk4cFxj2lSwXRO0',
    appId: '1:177666494702:android:915b31df7849af186ae3ff',
    messagingSenderId: '177666494702',
    projectId: 'stusama-revisi-ui',
    storageBucket: 'stusama-revisi-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzqVXQNWiKsqqWPDzHz8ue17YsTZD_T1M',
    appId: '1:177666494702:ios:e0b8c34694d44ba96ae3ff',
    messagingSenderId: '177666494702',
    projectId: 'stusama-revisi-ui',
    storageBucket: 'stusama-revisi-ui.appspot.com',
    iosBundleId: 'com.example.stusamaRevisiUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzqVXQNWiKsqqWPDzHz8ue17YsTZD_T1M',
    appId: '1:177666494702:ios:e0b8c34694d44ba96ae3ff',
    messagingSenderId: '177666494702',
    projectId: 'stusama-revisi-ui',
    storageBucket: 'stusama-revisi-ui.appspot.com',
    iosBundleId: 'com.example.stusamaRevisiUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH9bcg-xkt7vIBrjyuiPRqSltrJ-TFI0k',
    appId: '1:177666494702:web:34c4a270266bf8696ae3ff',
    messagingSenderId: '177666494702',
    projectId: 'stusama-revisi-ui',
    authDomain: 'stusama-revisi-ui.firebaseapp.com',
    storageBucket: 'stusama-revisi-ui.appspot.com',
  );
}
